import type {
  Comment,
  Like,
  MediaItem,
  MediaItemWithOwner,
  UserWithNoPassword,
} from 'hybrid-types/DBTypes';
import {useCallback, useEffect, useState} from 'react';
import {fetchData} from '../utils/fetch-data';
import type {
  Credentials,
  RegisterCredentials,
  UserDetails,
} from '../types/LocalTypes';
import type {
  AvailableResponse,
  LoginResponse,
  MediaResponse,
  MessageResponse,
  UploadResponse,
  UserResponse,
} from 'hybrid-types/MessageTypes';

const useMedia = () => {
  const [mediaArray, setMediaArray] = useState<MediaItemWithOwner[]>([]);

  useEffect(() => {
    const getMedia = async () => {
      try {
        const media = await fetchData<MediaItem[]>(
          import.meta.env.VITE_MEDIA_API + '/media',
        );
        const mediaWithOwners = await Promise.all<MediaItemWithOwner>(
          media.map(async (item) => {
            try {
              const owner = await fetchData<UserWithNoPassword>(
                `${import.meta.env.VITE_AUTH_API}/users/${item.user_id}`,
              );
              const mediaItemWithOwner: MediaItemWithOwner = {
                ...item,
                username: owner.username,
              };
              return mediaItemWithOwner;
            } catch (error) {
              console.error(error);
              return {
                ...item,
                username: 'not found',
              };
            }
          }),
        );
        setMediaArray(mediaWithOwners);
        console.log(mediaWithOwners);
      } catch (error) {
        console.error(error);
      }
    };

    getMedia();
  }, []);

  const postMedia = async (
    file: UploadResponse,
    inputs: Record<string, string>,
    token: string,
  ) => {
    // create a suitable object for Media API,
    // the type is MediaItem without media_id, user_id, thumbnail, screenshots, and created_at. All those are generated by the API.
    const mediaData = {
      ...file.data,
      ...inputs,
    };
    const options = {
      method: 'POST',
      headers: {
        Authorization: 'Bearer ' + token,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(mediaData),
    };
    // post the data to Media API and get the data as MediaResponse
    return fetchData<MediaResponse>(
      import.meta.env.VITE_MEDIA_API + '/media',
      options,
    );
  };

  return {mediaArray, postMedia};
};

const useAuthentication = () => {
  const postLogin = async (inputs: Credentials) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(inputs),
    };
    const loginResult = await fetchData<LoginResponse>(
      import.meta.env.VITE_AUTH_API + '/auth/login',
      fetchOptions,
    );
    return loginResult;
  };

  return {postLogin};
};

const useUser = () => {
  const resourceUrl = import.meta.env.VITE_AUTH_API + '/users';

  const postRegister = async (inputs: RegisterCredentials) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(inputs),
    };
    const registerResult = await fetchData(resourceUrl, fetchOptions);
    return registerResult;
  };

  const putUser = async (
    inputs: UserDetails,
    token: string,
  ): Promise<UserResponse> => {
    const fetchOptions = {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Bearer ' + token,
      },
      body: JSON.stringify(inputs),
    };
    const putResult = await fetchData<UserResponse>(resourceUrl, fetchOptions);
    return putResult;
  };

  const getUserByToken = useCallback(
    async (token: string) => {
      const options = {
        method: 'GET',
        headers: {
          Authorization: 'Bearer ' + token,
        },
      };
      return fetchData<UserResponse>(resourceUrl + '/token', options);
    },
    [resourceUrl],
  );

  const getUsernameAvailable = async (username: string) => {
    // fetch from endpoint /users/username/:username
    return fetchData<AvailableResponse>(`${resourceUrl}/username/${username}`);
  };

  const getEmailAvailable = async (email: string) => {
    // fetch from endpoint /users/email/:email
    return fetchData<AvailableResponse>(`${resourceUrl}/email/${email}`);
  };

  return {
    postRegister,
    putUser,
    getUserByToken,
    getUsernameAvailable,
    getEmailAvailable,
  };
};

const useFile = () => {
  const postFile = async (file: File, token: string) => {
    // create FormData object
    const formData = new FormData();
    // add file to FormData
    formData.append('file', file);
    // upload the file to file server and get the file data
    // return the file data. The type is UploadResponse
    const options = {
      method: 'POST',
      headers: {
        Authorization: 'Bearer ' + token,
      },
      body: formData,
    };
    return fetchData<UploadResponse>(
      import.meta.env.VITE_UPLOAD_API + '/upload',
      options,
    );
  };

  return {postFile};
};

const useLike = () => {
  const postLike = async (media_id: number, token: string) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Bearer ' + token,
      },
      body: JSON.stringify({media_id}),
    };
    return fetchData<MessageResponse>(
      import.meta.env.VITE_MEDIA_API + '/likes',
      fetchOptions,
    );
  };

  const deleteLike = async (like_id: number, token: string) => {
    // TODO: Send a DELETE request to /likes/:like_id with the token in the Authorization header.
    const fetchOptions = {
      method: 'DELETE',
      headers: {
        Authorization: 'Bearer ' + token,
      },
    };
    return fetchData<MessageResponse>(
      import.meta.env.VITE_MEDIA_API + '/likes/' + like_id,
      fetchOptions,
    );
  };

  const getCountByMediaId = async (media_id: number) => {
    // TODO: Send a GET request to /likes/count/:media_id to get the number of likes.
    return fetchData<{count: number}>(
      import.meta.env.VITE_MEDIA_API + '/likes/count/' + media_id,
    );
  };

  const getUserLike = async (media_id: number, token: string) => {
    // TODO: Send a GET request to /likes/bymedia/user/:media_id to get the user's like on the media.
    const fetchOptions = {
      method: 'GET',
      headers: {
        Authorization: 'Bearer ' + token,
      },
    };
    return fetchData<Like>(
      import.meta.env.VITE_MEDIA_API + '/likes/bymedia/user/' + media_id,
      fetchOptions,
    );
  };

  return {postLike, deleteLike, getCountByMediaId, getUserLike};
};

const useComment = () => {
  const postComment = async (
    comment_text: string,
    media_id: number,
    token: string,
  ) => {
    // Send a POST request to /comments with the comment object and the token in the Authorization header.
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Bearer ' + token,
      },
      body: JSON.stringify({media_id, comment_text}),
    };
    return fetchData<MessageResponse>(
      import.meta.env.VITE_MEDIA_API + '/comments',
      fetchOptions,
    );
  };

  const getCommentsByMediaId = async (id: number) => {
    // Send a GET request to /comments/bymedia/:media_id to get the comments.
    const comments = await fetchData<Comment[]>(
      import.meta.env.VITE_MEDIA_API + '/comments/bymedia/' + id,
    );
    // Send a GET requests to auth api and add usernames to all comments
    const commentsWithUsername = Promise.all<Comment & {username: string}>(
      comments.map(async (comment) => {
        const userInfo = await fetchData<UserWithNoPassword>(
          import.meta.env.VITE_AUTH_API + '/users/' + comment.user_id,
        );
        return {...comment, username: userInfo.username};
      }),
    );
    return commentsWithUsername;
  };

  return {postComment, getCommentsByMediaId};
};

export {useMedia, useAuthentication, useUser, useFile, useLike, useComment};
