import {cn} from '@/lib/utils';

const baseClassName =
  'border border-violet-300 px-4 py-2 focus:border-pink-500 focus:outline-none disabled:border-gray-200 disabled:bg-gray-50 disabled:text-gray-500 disabled:shadow-none';

// Generated by AI
const hasRounded = (cls?: string): boolean => {
  return Boolean(cls && /(^|\s)rounded(?:-|$)/.test(cls));
};

function Input({
  type = 'text',
  value,
  onChange,
  placeholder,
  className,
  ...props
}: React.ComponentProps<'input'>) {
  return (
    <input
      type={type}
      value={value}
      onChange={onChange}
      placeholder={placeholder}
      className={cn(
        baseClassName,
        !hasRounded(className) && 'rounded-md',
        className,
      )}
      {...props}
    />
  );
}

export default Input;
